# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

# device_info = [
# { :model_number => 'A1219', :internal_name => 'k48ap', :identifier => 'iPad1,1', :name => 'iPad', :image => 'ipad.png', :min_os_id => 8, :max_os_id => 15 },
# { :model_number => 'A1337', :internal_name => 'k48ap', :identifier => 'iPad1,1', :name => 'iPad', :image => 'ipad.png', :min_os_id => 8, :max_os_id => 15 },
# { :model_number => 'A1395', :internal_name => 'k93ap', :identifier => 'iPad2,1', :name => 'iPad 2', :image => 'ipad_2.png', :min_os_id => 11, :max_os_id => 25 },
# { :model_number => 'A1396', :internal_name => 'k94ap', :identifier => 'iPad2,2', :name => 'iPad 2', :image => 'ipad_2.png', :min_os_id => 11, :max_os_id => 25 },
# { :model_number => 'A1397', :internal_name => 'k95ap', :identifier => 'iPad2,3', :name => 'iPad 2', :image => 'ipad_2.png', :min_os_id => 11, :max_os_id => 25 },
# { :model_number => 'A1395', :internal_name => 'k93aap', :identifier => 'iPad2,4', :name => 'iPad 2', :image => 'ipad_2.png', :min_os_id => 11, :max_os_id => 25 },
# { :model_number => 'A1416', :internal_name => 'j1ap', :identifier => 'iPad3,1', :name => 'iPad 3', :image => 'ipad_3.png', :min_os_id => 14, :max_os_id => 25 },
# { :model_number => 'A1403', :internal_name => 'j2ap', :identifier => 'iPad3,2', :name => 'iPad 3', :image => 'ipad_3.png', :min_os_id => 14, :max_os_id => 25 },
# { :model_number => 'A1430', :internal_name => 'j2aap', :identifier => 'iPad3,3', :name => 'iPad 3', :image => 'ipad_3.png', :min_os_id => 14, :max_os_id => 25 },
# { :model_number => 'A1458', :internal_name => 'p101ap', :identifier => 'iPad3,4', :name => 'iPad 4', :image => 'ipad_4.png', :min_os_id => 16, :max_os_id => 25 },
# { :model_number => 'A1459', :internal_name => 'p102ap', :identifier => 'iPad3,5', :name => 'iPad 4', :image => 'ipad_4.png', :min_os_id => 17, :max_os_id => 25 },
# { :model_number => 'A1460', :internal_name => 'p103ap', :identifier => 'iPad3,6', :name => 'iPad 4', :image => 'ipad_4.png', :min_os_id => 17, :max_os_id => 25 },
# { :model_number => 'A1474', :internal_name => 'j71ap', :identifier => 'iPad4,1', :name => 'iPad Air', :image => 'ipad_air.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1475', :internal_name => 'j72ap', :identifier => 'iPad4,2', :name => 'iPad Air', :image => 'ipad_air.png', :min_os_id => 20, :max_os_id => 25 },
# { :model_number => 'A1476', :internal_name => 'j73ap', :identifier => 'iPad4,3', :name => 'iPad Air', :image => 'ipad_air.png', :min_os_id => 20, :max_os_id => 25 },
# { :model_number => 'A1566', :internal_name => 'j81ap', :identifier => 'iPad5,3', :name => 'iPad Air 2', :image => 'ipad_air_2.png', :min_os_id => 23, :max_os_id => 25 },
# { :model_number => 'A1567', :internal_name => 'j82ap', :identifier => 'iPad5,4', :name => 'iPad Air 2', :image => 'ipad_air_2.png', :min_os_id => 23, :max_os_id => 25 },
# { :model_number => 'A1432', :internal_name => 'p105ap', :identifier => 'iPad2,5', :name => 'iPad mini 1G', :image => 'ipad_mini.png', :min_os_id => 16, :max_os_id => 25 },
# { :model_number => 'A1454', :internal_name => 'p106ap', :identifier => 'iPad2,6', :name => 'iPad mini 1G', :image => 'ipad_mini.png', :min_os_id => 17, :max_os_id => 25 },
# { :model_number => 'A1455', :internal_name => 'p107ap', :identifier => 'iPad2,7', :name => 'iPad mini 1G', :image => 'ipad_mini.png', :min_os_id => 17, :max_os_id => 25 },
# { :model_number => 'A1489', :internal_name => 'j85ap', :identifier => 'iPad4,4', :name => 'iPad mini 2', :image => 'ipad_mini_2.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1490', :internal_name => 'j86ap', :identifier => 'iPad4,5', :name => 'iPad mini 2', :image => 'ipad_mini_2.png', :min_os_id => 20, :max_os_id => 25 },
# { :model_number => 'A1491', :internal_name => 'j87ap', :identifier => 'iPad4,6', :name => 'iPad mini 2', :image => 'ipad_mini_2.png', :min_os_id => 20, :max_os_id => 25 },
# { :model_number => 'A1599', :internal_name => 'j85map', :identifier => 'iPad4,7', :name => 'iPad mini 3', :image => 'ipad_mini_3.png', :min_os_id => 22, :max_os_id => 25 },
# { :model_number => 'A1600', :internal_name => 'j86map', :identifier => 'iPad4,8', :name => 'iPad mini 3', :image => 'ipad_mini_3.png', :min_os_id => 23, :max_os_id => 25 },
# { :model_number => 'A1601', :internal_name => 'j87map', :identifier => 'iPad4,9', :name => 'iPad mini 3', :image => 'ipad_mini_3.png', :min_os_id => 23, :max_os_id => 25 },
# { :model_number => 'A1203', :internal_name => 'm68ap', :identifier => 'iPhone1,1', :name => 'iPhone', :image => 'iphone.png', :min_os_id => 1, :max_os_id => 6 },
# { :model_number => 'A1241', :internal_name => 'n82ap', :identifier => 'iPhone1,2', :name => 'iPhone 3G', :image => 'iphone_3g.png', :min_os_id => 3, :max_os_id => 11 },
# { :model_number => 'A1324', :internal_name => 'n82ap', :identifier => 'iPhone1,2', :name => 'iPhone 3G', :image => 'iphone_3g.png', :min_os_id => 3, :max_os_id => 11 },
# { :model_number => 'A1303', :internal_name => 'n88ap', :identifier => 'iPhone2,1', :name => 'iPhone 3GS', :image => 'iphone_3gs.png', :min_os_id => 5, :max_os_id => 18 },
# { :model_number => 'A1325', :internal_name => 'n88ap', :identifier => 'iPhone2,1', :name => 'iPhone 3GS', :image => 'iphone_3gs.png', :min_os_id => 5, :max_os_id => 18 },
# { :model_number => 'A1332', :internal_name => 'n90ap', :identifier => 'iPhone3,1', :name => 'iPhone 4', :image => 'iphone_4.png', :min_os_id => 9, :max_os_id => 21 },
# { :model_number => 'A1332*', :internal_name => 'n90bap', :identifier => 'iPhone3,2', :name => 'iPhone 4', :image => 'iphone_4.png', :min_os_id => 9, :max_os_id => 21 },
# { :model_number => 'A1349', :internal_name => 'n92ap', :identifier => 'iPhone3,3', :name => 'iPhone 4', :image => 'iphone_4.png', :min_os_id => 12, :max_os_id => 21 },
# { :model_number => 'A1387', :internal_name => 'n94ap', :identifier => 'iPhone4,1', :name => 'iPhone 4S', :image => 'iphone_4s.png', :min_os_id => 13, :max_os_id => 25 },
# { :model_number => 'A1431', :internal_name => 'n94ap', :identifier => 'iPhone4,1', :name => 'iPhone 4S', :image => 'iphone_4s.png', :min_os_id => 13, :max_os_id => 25 },
# { :model_number => 'A1428', :internal_name => 'n41ap', :identifier => 'iPhone5,1', :name => 'iPhone 5', :image => 'iphone_5.png', :min_os_id => 16, :max_os_id => 25 },
# { :model_number => 'A1429', :internal_name => 'n42ap', :identifier => 'iPhone5,2', :name => 'iPhone 5', :image => 'iphone_5.png', :min_os_id => 16, :max_os_id => 25 },
# { :model_number => 'A1442', :internal_name => 'n42ap', :identifier => 'iPhone5,2', :name => 'iPhone 5', :image => 'iphone_5.png', :min_os_id => 16, :max_os_id => 25 },
# { :model_number => 'A1456', :internal_name => 'n48ap', :identifier => 'iPhone5,3', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1532', :internal_name => 'n48ap', :identifier => 'iPhone5,3', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1507', :internal_name => 'n48ap', :identifier => 'iPhone5,4', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1516', :internal_name => 'n48ap', :identifier => 'iPhone5,4', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1526', :internal_name => 'n48ap', :identifier => 'iPhone5,4', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1529', :internal_name => 'n48ap', :identifier => 'iPhone5,4', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1529*', :internal_name => 'n49ap', :identifier => 'iPhone5,4', :name => 'iPhone 5c', :image => 'iphone_5c.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1453', :internal_name => 'n51ap', :identifier => 'iPhone6,1', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1533', :internal_name => 'n51ap', :identifier => 'iPhone6,1', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1457', :internal_name => 'n51ap', :identifier => 'iPhone6,1', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1518', :internal_name => 'n51ap', :identifier => 'iPhone6,1', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1528', :internal_name => 'n51ap', :identifier => 'iPhone6,1', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1530', :internal_name => 'n53ap', :identifier => 'iPhone6,2', :name => 'iPhone 5s', :image => 'iphone_5s.png', :min_os_id => 19, :max_os_id => 25 },
# { :model_number => 'A1549', :internal_name => 'n61ap', :identifier => 'iPhone7,2', :name => 'iPhone 6', :image => 'iphone_6.png', :min_os_id => 22, :max_os_id => 25 },
# { :model_number => 'A1522', :internal_name => 'n56ap', :identifier => 'iPhone7,1', :name => 'iPhone 6 Plus', :image => 'iphone_6plus.png', :min_os_id => 22, :max_os_id => 25 },
# { :model_number => 'A1524', :internal_name => 'n56ap', :identifier => 'iPhone7,1', :name => 'iPhone 6 Plus', :image => 'iphone_6plus.png', :min_os_id => 22, :max_os_id => 25 }
# ]

# device_info.each do |device_hash|
#   d = Device.new
#   d.manufacturer_id = 1
#   d.model_number = device_hash[:model_number]
#   d.internal_name = device_hash[:internal_name]
#   d.identifier = device_hash[:identifier]
#   d.name = device_hash[:name]
#   d.image = device_hash[:image]
#   d.save
# end

# puts "There are now #{Device.count} devices in the database."


# opsystem_info = [
# { :manufacturer_id => 1, :version_name => 'iPhone OS 1.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 1.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 2.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 2.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 3.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 3.1.1 (8 GB "MC" model)', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iPhone OS 3.1.3', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 3.2', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 4.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 4.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 4.2.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 4.2.2', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 5.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 5.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 5.1.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 6.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 6.0.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 6.1.6', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 7.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 7.0.3', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 7.1.2', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 8.0', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 8.1', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 8.4', :is_current => 0 },
# { :manufacturer_id => 1, :version_name => 'iOS 8.4.1', :is_current => 0 }
# ]

# opsystem_info.each do |os_hash|
#   o = Opsystem.new
#   o.manufacturer_id = os_hash[:manufacturer_id]
#   o.version_name = os_hash[:version_name]
#   o.is_current = os_hash[:is_current]
#   o.save
# end

# puts "There are now #{Opsystem.count} OpSystems in the database."

# a = Manufacturer.new
# a.name = "Apple"

# puts "'Apple' has been entered into Manufacturers in the database."

activity_info = [
  { :name => 'Aircraft Spotting' },
  { :name => 'Airbrushing' },
  { :name => 'Airsofting' },
  { :name => 'Acting' },
  { :name => 'Aeromodeling' },
  { :name => 'Amateur Astronomy' },
  { :name => 'Amateur Radio' },
  { :name => 'Animals/pets/dogs' },
  { :name => 'Archery' },
  { :name => 'Arts' },
  { :name => 'Aquarium (Freshwater & Saltwater)' },
  { :name => 'Astrology' },
  { :name => 'Astronomy' },
  { :name => 'Backgammon' },
  { :name => 'Badminton' },
  { :name => 'Baseball' },
  { :name => 'Base Jumping' },
  { :name => 'Basketball' },
  { :name => 'Beach/Sun tanning' },
  { :name => 'Beachcombing' },
  { :name => 'Beadwork' },
  { :name => 'Beatboxing' },
  { :name => 'Becoming A Child Advocate' },
  { :name => 'Bell Ringing' },
  { :name => 'Belly Dancing' },
  { :name => 'Bicycling' },
  { :name => 'Bicycle Polo' },
  { :name => 'Bird watching' },
  { :name => 'Birding' },
  { :name => 'BMX' },
  { :name => 'Blacksmithing' },
  { :name => 'Blogging' },
  { :name => 'BoardGames' },
  { :name => 'Boating' },
  { :name => 'Body Building' },
  { :name => 'Bonsai Tree' },
  { :name => 'Bookbinding' },
  { :name => 'Boomerangs' },
  { :name => 'Bowling' },
  { :name => 'Brewing Beer' },
  { :name => 'Bridge Building' },
  { :name => 'Bringing Food To The Disabled' },
  { :name => 'Building A House For Habitat For Humanity' },
  { :name => 'Building Dollhouses' },
  { :name => 'Butterfly Watching' },
  { :name => 'Button Collecting' },
  { :name => 'Cake Decorating' },
  { :name => 'Calligraphy' },
  { :name => 'Camping' },
  { :name => 'Candle Making' },
  { :name => 'Canoeing' },
  { :name => 'Cartooning' },
  { :name => 'Car Racing' },
  { :name => 'Casino Gambling' },
  { :name => 'Cave Diving' },
  { :name => 'Ceramics' },
  { :name => 'Cheerleading' },
  { :name => 'Chess' },
  { :name => 'Church/church activities' },
  { :name => 'Cigar Smoking' },
  { :name => 'Cloud Watching' },
  { :name => 'Coin Collecting' },
  { :name => 'Collecting' },
  { :name => 'Collecting Antiques' },
  { :name => 'Collecting Artwork' },
  { :name => 'Collecting Hats' },
  { :name => 'Collecting Music Albums' },
  { :name => 'Collecting RPM Records' },
  { :name => 'Collecting Sports Cards (Baseball, Football, Basketball, Hockey)' },
  { :name => 'Collecting Swords' },
  { :name => 'Coloring' },
  { :name => 'Compose Music' },
  { :name => 'Computer activities' },
  { :name => 'Conworlding' },
  { :name => 'Cooking' },
  { :name => 'Cosplay' },
  { :name => 'Crafts' },
  { :name => 'Crafts (unspecified)' },
  { :name => 'Crochet' },
  { :name => 'Crocheting' },
  { :name => 'Cross-Stitch' },
  { :name => 'Crossword Puzzles' },
  { :name => 'Dancing' },
  { :name => 'Darts' },
  { :name => 'Diecast Collectibles' },
  { :name => 'Digital Photography' },
  { :name => 'Dodgeball' },
  { :name => 'Dolls' },
  { :name => 'Dominoes' },
  { :name => 'Drawing' },
  { :name => 'Dumpster Diving' },
  { :name => 'Eating out' },
  { :name => 'Educational Courses' },
  { :name => 'Electronics' },
  { :name => 'Embroidery' },
  { :name => 'Entertaining' },
  { :name => 'Exercise (aerobics, weights)' },
  { :name => 'Falconry' },
  { :name => 'Fast cars' },
  { :name => 'Felting' },
  { :name => 'Fencing' },
  { :name => 'Fire Poi' },
  { :name => 'Fishing' },
  { :name => 'Floorball' },
  { :name => 'Floral Arrangements' },
  { :name => 'Fly Tying' },
  { :name => 'Football' },
  { :name => 'Four Wheeling' },
  { :name => 'Freshwater Aquariums' },
  { :name => 'Frisbee Golf – Frolf' },
  { :name => 'Games' },
  { :name => 'Gardening' },
  { :name => 'Garage Saleing' },
  { :name => 'Genealogy' },
  { :name => 'Geocaching' },
  { :name => 'Ghost Hunting' },
  { :name => 'Glowsticking' },
  { :name => 'Gnoming' },
  { :name => 'Going to movies' },
  { :name => 'Golf' },
  { :name => 'Go Kart Racing' },
  { :name => 'Grip Strength' },
  { :name => 'Guitar' },
  { :name => 'Gunsmithing' },
  { :name => 'Gun Collecting' },
  { :name => 'Gymnastics' },
  { :name => 'Gyotaku' },
  { :name => 'Handwriting Analysis' },
  { :name => 'Hang gliding' },
  { :name => 'Herping' },
  { :name => 'Hiking' },
  { :name => 'Home Brewing' },
  { :name => 'Home Repair' },
  { :name => 'Home Theater' },
  { :name => 'Horse riding' },
  { :name => 'Hot air ballooning' },
  { :name => 'Hula Hooping' },
  { :name => 'Hunting' },
  { :name => 'Iceskating' },
  { :name => 'Illusion' },
  { :name => 'Impersonations' },
  { :name => 'Internet' },
  { :name => 'Inventing' },
  { :name => 'Jet Engines' },
  { :name => 'Jewelry Making' },
  { :name => 'Jigsaw Puzzles' },
  { :name => 'Juggling' },
  { :name => 'Keep A Journal' },
  { :name => 'Jump Roping' },
  { :name => 'Kayaking' },
  { :name => 'Kitchen Chemistry' },
  { :name => 'Kites' },
  { :name => 'Kite Boarding' },
  { :name => 'Knitting' },
  { :name => 'Knotting' },
  { :name => 'Lasers' },
  { :name => 'Lawn Darts' },
  { :name => 'Learn to Play Poker' },
  { :name => 'Learning A Foreign Language' },
  { :name => 'Learning An Instrument' },
  { :name => 'Learning To Pilot A Plane' },
  { :name => 'Leathercrafting' },
  { :name => 'Legos' },
  { :name => 'Letterboxing' },
  { :name => 'Listening to music' },
  { :name => 'Locksport' },
  { :name => 'Lacrosse' },
  { :name => 'Macramé' },
  { :name => 'Magic' },
  { :name => 'Making Model Cars' },
  { :name => 'Marksmanship' },
  { :name => 'Martial Arts' },
  { :name => 'Matchstick Modeling' },
  { :name => 'Meditation' },
  { :name => 'Microscopy' },
  { :name => 'Metal Detecting' },
  { :name => 'Model Railroading' },
  { :name => 'Model Rockets' },
  { :name => 'Modeling Ships' },
  { :name => 'Models' },
  { :name => 'Motorcycles' },
  { :name => 'Mountain Biking' },
  { :name => 'Mountain Climbing' },
  { :name => 'Musical Instruments' },
  { :name => 'Nail Art' },
  { :name => 'Needlepoint' },
  { :name => 'Owning An Antique Car' },
  { :name => 'Origami' },
  { :name => 'Painting' },
  { :name => 'Paintball' },
  { :name => 'Papermaking' },
  { :name => 'Papermache' },
  { :name => 'Parachuting' },
  { :name => 'Paragliding or Power Paragliding' },
  { :name => 'Parkour' },
  { :name => 'People Watching' },
  { :name => 'Photography' },
  { :name => 'Piano' },
  { :name => 'Pinochle' },
  { :name => 'Pipe Smoking' },
  { :name => 'Planking' },
  { :name => 'Playing music' },
  { :name => 'Playing team sports' },
  { :name => 'Pole Dancing' },
  { :name => 'Pottery' },
  { :name => 'Powerboking' },
  { :name => 'Protesting' },
  { :name => 'Puppetry' },
  { :name => 'Pyrotechnics' },
  { :name => 'Quilting' },
  { :name => 'Racing Pigeons' },
  { :name => 'Rafting' },
  { :name => 'Railfans' },
  { :name => 'Rapping' },
  { :name => 'R/C Boats' },
  { :name => 'R/C Cars' },
  { :name => 'R/C Helicopters' },
  { :name => 'R/C Planes' },
  { :name => 'Reading' },
  { :name => 'Reading To The Elderly' },
  { :name => 'Relaxing' },
  { :name => 'Renaissance Faire' },
  { :name => 'Renting movies' },
  { :name => 'Rescuing Abused Or Abandoned Animals' },
  { :name => 'Robotics' },
  { :name => 'Rock Balancing' },
  { :name => 'Rock Collecting' },
  { :name => 'Rockets' },
  { :name => 'Rocking AIDS Babies' },
  { :name => 'Roleplaying' },
  { :name => 'Running' },
  { :name => 'Saltwater Aquariums' },
  { :name => 'Sand Castles' },
  { :name => 'Scrapbooking' },
  { :name => 'Scuba Diving' },
  { :name => 'Self Defense' },
  { :name => 'Sewing' },
  { :name => 'Shark Fishing' },
  { :name => 'Skeet Shooting' },
  { :name => 'Skiing' },
  { :name => 'Shopping' },
  { :name => 'Singing In Choir' },
  { :name => 'Skateboarding' },
  { :name => 'Sketching' },
  { :name => 'Sky Diving' },
  { :name => 'Slack Lining' },
  { :name => 'Sleeping' },
  { :name => 'Slingshots' },
  { :name => 'Slot Car Racing' },
  { :name => 'Snorkeling' },
  { :name => 'Snowboarding' },
  { :name => 'Soap Making' },
  { :name => 'Soccer' },
  { :name => 'Socializing with friends/neighbors' },
  { :name => 'Speed Cubing (rubix cube)' },
  { :name => 'Spelunkering' },
  { :name => 'Spending time with family/kids' },
  { :name => 'Stamp Collecting' },
  { :name => 'Storm Chasing' },
  { :name => 'Storytelling' },
  { :name => 'String Figures' },
  { :name => 'Surfing' },
  { :name => 'Surf Fishing' },
  { :name => 'Survival' },
  { :name => 'Swimming' },
  { :name => 'Tatting' },
  { :name => 'Taxidermy' },
  { :name => 'Tea Tasting' },
  { :name => 'Tennis' },
  { :name => 'Tesla Coils' },
  { :name => 'Tetris' },
  { :name => 'Texting' },
  { :name => 'Textiles' },
  { :name => 'Tombstone Rubbing' },
  { :name => 'Tool Collecting' },
  { :name => 'Toy Collecting' },
  { :name => 'Train Collecting' },
  { :name => 'Train Spotting' },
  { :name => 'Traveling' },
  { :name => 'Treasure Hunting' },
  { :name => 'Trekkie' },
  { :name => 'Tutoring Children' },
  { :name => 'TV watching' },
  { :name => 'Ultimate Frisbee' },
  { :name => 'Urban Exploration' },
  { :name => 'Video Games' },
  { :name => 'Violin' },
  { :name => 'Volunteer' },
  { :name => 'Walking' },
  { :name => 'Warhammer' },
  { :name => 'Watching sporting events' },
  { :name => 'Weather Watcher' },
  { :name => 'Weightlifting' },
  { :name => 'Windsurfing' },
  { :name => 'Wine Making' },
  { :name => 'Wingsuit Flying' },
  { :name => 'Woodworking' },
  { :name => 'Working In A Food Pantry' },
  { :name => 'Working on cars' },
  { :name => 'World Record Breaking' },
  { :name => 'Wrestling' },
  { :name => 'Writing' },
  { :name => 'Writing Music' },
  { :name => 'Writing Songs' },
  { :name => 'Yoga' },
  { :name => 'YoYo' },
  { :name => 'Ziplining' },
  { :name => 'Zumba' }
]

activity_info.each do |activity|
  o = Activity.new
  o.name = activity[:name]
  o.save
end

puts "There are now #{Activity.count} Activities in the database."
